"""Canonical Claude zero-shot AI-text classifier.

Defined ONCE here and imported by BOTH Notebook 4 (the eval) and the Phase 2 FastAPI service,
so the production endpoint behaves identically to the evaluated model (no prompt drift).

The prompt + label parsing are the single source of truth. Notebook 4 wraps `classify_text`
with a file cache + rate-limit retry (eval-only concerns); the API calls it directly.
"""
from __future__ import annotations

# Single source of truth for the zero-shot prompt.
PROMPT_TEMPLATE = (
    "Classify whether the following text was written by a human or generated by an AI. "
    "Reply with ONLY a single digit: 0 for human, 1 for AI. No explanation.\n\n"
    "Text: {text}\n\nAnswer:"
)

DEFAULT_MODEL = "claude-haiku-4-5"

# Claude Haiku 4.5 list price, USD per 1M tokens. Verify at https://www.anthropic.com/pricing.
CLAUDE_PRICING = {"in_per_mtok": 1.0, "out_per_mtok": 5.0}


def classify_text(client, text: str, model: str = DEFAULT_MODEL, max_chars: int = 12_000):
    """One Claude call + parse. Pure (no caching, no retry).

    Returns ``(label, raw_content, usage)`` where label is 0=human, 1=AI, or None if the reply
    could not be parsed. ``usage`` is the Anthropic usage object (``input_tokens`` / ``output_tokens``).
    """
    resp = client.messages.create(
        model=model,
        max_tokens=4,
        messages=[{"role": "user", "content": PROMPT_TEMPLATE.format(text=text[:max_chars])}],
    )
    content = resp.content[0].text.strip()
    label = 0 if content.startswith("0") else 1 if content.startswith("1") else None
    return label, content, resp.usage


def cost_usd(usage) -> float:
    """USD cost of one call from an Anthropic usage object."""
    return (usage.input_tokens * CLAUDE_PRICING["in_per_mtok"]
            + usage.output_tokens * CLAUDE_PRICING["out_per_mtok"]) / 1_000_000
